version: '3'
services:
    mysqld:
        image: oshp/database:develop
        networks:
          - traefik-net
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: headers
          MYSQL_USER: mysql
          MYSQL_PASSWORD: password
        deploy:
          replicas: 1
          restart_policy:
            condition: on-failure
          resources:
            limits:
              memory: 200M
    oshp:
        image: oshp/secureheaders:3.1.0
        networks:
          - traefik-net
        deploy:
          labels:
            - traefik.enable=true
            - traefik.backend=oshp
            - traefik.port=5000
            - traefik.backend.loadbalancer.method=drr
            - traefik.frontend.rule=Host:oshp.bsecteam.com
          replicas: 1
          restart_policy:
            condition: on-failure
          resources:
            limits:
              memory: 100M
    traefik:
        image: traefik:1.3-alpine
        networks:
          - traefik-net
        command: --docker.swarmmode --docker.watch --docker.exposedbydefault=false --docker.domain=bsecteam.com --web --web.statistics --web.metrics
        ports:
          - 80:80
          - 8080:8080
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        deploy:
          replicas: 1
          restart_policy:
            condition: on-failure
          resources:
            limits:
              memory: 50M
          placement:
            constraints:
              - node.role == manager
    redis:
        image: redis:alpine
        networks:
          - traefik-net
        deploy:
          replicas: 1
          restart_policy:
            condition: on-failure
          resources:
            limits:
              memory: 5M
networks:
  traefik-net:
    driver: overlay
